### ISSUE TITLE
Gemeinnuetzigkeit

### ISSUE THREAD

**Issue by Cat-Ion** [HackerspaceBT/Dokumente#3]
Das Finanzamt ist unzufrieden mit der aktuellen Version unserer Satzung. Laut Cyrus muessen wir...

- die Foerderung von Kultur aus dem Zweck entfernen, da das Finanzamt eine obsolete Version von Kultur installiert hat
- die Umsetzung so anpassen, dass offensichtlich wird, dass sich alle Angebote an die Allgemeinheit richten (nichts mit 'Angestellte und Kunden von Telekommunikationsunternehmen')

War's das?

**Comment by MichaelBuchhorn** [comment]
Scheinbar sollen wir laut Cyrus auch noch genauer Ausführen, wie wir Wissenschaft fördern wollen.

**Comment by Cat-Ion** [comment]
Sollte mit den aktuellen Aenderungen passen. Ich schliess den Bug erst mal und hoffe, dass er so bleiben kann.
